### ISSUE TITLE
Ein-Klick-Farmen

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#101]
Wird öfter mal gefordert.

**Comment by schwertkriege-de** [comment]
Ein Update.

**Comment by Ares61** [comment]
Ist nun per doppel klick => Gebäude bauen drin.
Close wenn keine Beschwerden kommen

**Comment by schwertkriege-de** [comment]
Mit `ondblclick` umgesetzt.
Das heißt: aktuelle Blinks & Firefox _kein_ mobile.
https://caniuse.com/#feat=mdn-api_globaleventhandlers_ondblclick

**Comment by Ares61** [comment]
wie gehen wir hier vor? entfernen wieder?

**Comment by schwertkriege-de** [comment]
nö, passt.
