### ISSUE TITLE
Einheitenausbildung: Anzeige-Sortierungsfehler?

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#103]
![image](https://user-images.githubusercontent.com/59437220/73120342-ff45be00-3f6c-11ea-97f4-184eb7806f06.png)

danach war die Armbrust fertig und nicht der Bogen.

**Comment by Ares61** [comment]
nein dies ist kein Sortierungsfehler.
Es wird nicht nach klasse sortiert.. sondern nach ausbildungsreihenfolge.
Anschließend wird die Info komprimiert.

Sprich es kann folgendes vorkommen:
Bogen 1x
armbrust 1x
Bogen 1x
Armbrust 1x
Bogen 2x
Arm 1x

**Comment by Ares61** [comment]
fixed.
