### ISSUE TITLE
Armeen Merge: Moralberechnung buggy?

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#146]
> Ich habe gerade 2 Armeen zusammengelegt
> 
> Armee 1 : 200 Soldaten, 84% Moral
> Armee 2: 1 Soldat, 54% Moral
> Neue Armee 64% Moral

**Comment by schwertkriege-de** [comment]
SirSmoke hat das auch in der SR Nyx gemeldet.
Ich konnte es nicht nachstellen, es kommt wohl nur gelegentlich vor, leider unklar wann.

Andere Baustelle: Die Berechnung an sich ist insofern unrund, als das in einer foreach jede Armee einzeln zur Moralberechnung drankommt und der Wert floored wird.

**Comment by ghbob** [comment]
Ist behoben, die erste Armee hatte zusätzlich das Gewicht der zweiten Armee.

**Comment by schwertkriege-de** [comment]
Ist behoben, die erste Armee hatte das Gewicht der zweiten zusätzlich.
