### ISSUE TITLE
Userpage 2020

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#37]
- [x] flexbox (aka popup-neu)
- [x] optisch überholen
- [x] Beschreibungstext (500 Zeichen), zentriert dargestellt, bold und italic
- [x] profilbild?

**Comment by schwertkriege-de** [comment]
@Ares61 du warst da eh schon fleissig, ich hab das ding jetzt etwas extended :)

**Comment by Ares61** [comment]
erledigt,

**Comment by schwertkriege-de** [comment]
- [ ] Müssen wir die Werte die wir hier als `img src` ausgeben validieren? kann man damit unfug treiben?
- [ ] css nach gfx
- [ ] `cursor:pointer;` in der rangliste

@Ares61

**Comment by Ares61** [comment]
die img src brauchen wir nicht validieren.

**Comment by Ares61** [comment]
erledigt.

**Comment by schwertkriege-de** [comment]
- [ ]  Link auf den Benutzer in der Sektoransicht wieder entfernen dort ist das wichtige der Provinzlink. Über diesen (siehe auch #116) kann man dann auch den Benutzer auswählen.
