### ISSUE TITLE
max. drei Städte pro Sektor

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#47]
Um gesammelte Stadtsektoren pro Fürstentum zu vermeiden.

**Comment by schwertkriege-de** [comment]
Bitte auch prüfen ob das hier stimmt:
Pro Spieler kann max. eine Stadt pro Sektor gegründet werden.

**Comment by Ares61** [comment]
Pro Spieler kann nur 1 stadt pro Sektor.
Pro Sektor können max 3 Städte.
Erledigt.
