### ISSUE TITLE
klassische Ansicht hüpft aufgrund des grids

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#52]
![image](https://user-images.githubusercontent.com/59437220/72221768-f6f98600-355d-11ea-9185-f5c0568117aa.png)

![image](https://user-images.githubusercontent.com/59437220/72221771-feb92a80-355d-11ea-95ea-253f85c8932d.png)

**Comment by Ares61** [comment]
erledigt.
