### ISSUE TITLE
stündliche Einnahmen/Ausgaben im Header anzeigen

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#78]
Nachdem die Info super spielrelevant ist und spätestens mit dem (Wieder-) Einführen von laufenden Kosten dem Spieler besser angezeigt werden muss.

**Optionen**:
a) Header erweitern und unter den vorhandenen Ressourcen die Info anzeigen
b) Mit Klick auf die Ressource die Infobox mit der Info anzeigen (reicht denke ich nicht, macht keiner)
c) Wenn man auf den Header klickt umschalten zwischen 1. Aktuellen Ressoucen, 2. Stündlichen Einnahmen/Ausgaben, 3. Tägliche Einnahmen Ausgaben. Dazu brauchts evtl. nochmal ein gesondertes Icon damit diese Funktion für jeden ersichtlich ist!

c) Wäre denk ich ne gute Option nachdem a) auch einiges an Design Aufwand bedeuten würde.

**Comment by Ares61** [comment]
erledigt.
