### ISSUE TITLE
Armeen: Ankunftszeiten besser ersichtlich machen

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#79]
Wenn man auf den Button einer laufenden Armee klickt bekommt man die genauen Ankunftszeiten in allen Provinzen (alt war das ein Popup, neu ist dass einer der hübschen overlay boxen).

Das ist vielen Leuten nicht bewusst, daher:

a) dedizierter Button mit Icon damit diese Funktion besser ersichtlich ist
und / oder
b) die finale Ankunftszeit (der Zielprovinz) auch in der Zeile der Armee direkt anzeigen.

**Comment by Ares61** [comment]
Ankunftszeiten sind nun besser ersichtlich.
Detaillierteres kommt irgendwann mit dem Neuaufbau der Seite
