### ISSUE TITLE
Bauschleife: springt nicht korrekt weiter

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#84]
Das aktuelle Gebäude wird fertig dargestellt, aber was danach passiert haut nicht so recht hin:

Weder das Anfangen eines neues Gebäudes in der Schleife, noch das Verteilen der Arbeiter nach dem letzten Gebäude in der Schleife.

Rein optisch, im Hintergrund scheint alles richtig zu laufen.

**Comment by Ares61** [comment]
erledigt.
