### ISSUE TITLE
Wirtschaft, Ausbilden, Infobox: Info in wievielen Gebäuden ausgebildet wird

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#91]
![image](https://user-images.githubusercontent.com/59437220/72803969-ac5bc600-3c4f-11ea-9f32-c8b6438f2ef4.png)

@Ares61 die box wird ja vom Server befüllt, das heißt wenn wir da mitzählen auf wieviele DZs/andere Gebäude das verteilt wird können wir das dazuschreiben? Wäre recht praktisch :)

**Comment by schwertkriege-de** [comment]
Beispiel: 
> 7 Arbeiter auf 7 Dorfzentren verteilt in Auftrag gegeben

**Comment by Ares61** [comment]
erledigt,
