### ISSUE TITLE
Armee zusammenführen funktioniert nicht auf EME prov

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#92]
> Was mir gerade auffällt. Stehe auf einer prov von nem Mitstreiter, kann meine armee aber nicht zusammenführen.
> In dieser Provinz befindet sich leider nur eine Armee. Armeen, die marschieren oder die sich im Kampf befinden, können nicht zusammengelegt werden.

**Comment by schwertkriege-de** [comment]
> "In dieser Provinz befindet sich leider nur eine Armee. Armeen, die marschieren oder die sich im Kampf befinden, können nicht zusammengelegt werden."
> 
> 
> Ich befinde mich auf einer befreundeten Provinz eines Allykollegen mit 4 Einzelarmeen. Diese Meldung oben taucht auf, wenn ich meine Armeen zusammenlegen will. Meine Armeen sind alle stehend (keine regeneriert). Eine Armee von einem Allykollegen läuft noch drüber.

**Comment by Ares61** [comment]
erledigt.
