### ISSUE TITLE
Stadtgründung: immer anzeigen

### ISSUE THREAD

**Issue by schwertkriege-de** [schwertkriege-de/issues#98]
Es fehlt ein wenig die Info, dass es da was gibt.
Man weiß auch die Anforderungen nicht so wirklich.
Wäre gut wenn man dafür vorplanen kann (zB braucht man 10k Holz wenn ich den Wert erreicht, etc.)

Generelle Frage: verstecken wir dort sonst noch was?
Branden war glaub ich noch ausgeblendet bis man die 10 prov hürde (oder so) erreicht hat.

**Comment by schwertkriege-de** [comment]
![image](https://user-images.githubusercontent.com/59437220/73118622-eb8f5d00-3f56-11ea-9d3d-ef35fd0b5403.png)

und aufgehübscht gehört die Seite wohl auch :)

**Comment by Ares61** [comment]
erledigt.
